import type { ProviderProfile } from "@/modules/video-generation/governance/types";

export const PROVIDER_REGISTRY: ProviderProfile[] = [
  {
    apiReadiness: 0.85,
    cameraScore: 0.92,
    costTier: "high",
    environmentComplexitySupport: 0.78,
    failureRate: 0.12,
    id: "wan",
    maxDuration: 12,
    motionScore: 0.81,
    name: "WAN",
    offlineLocalSupport: false,
    portraitSupport: 0.7,
    queueSpeed: 0.48,
    queueStability: 0.66,
    realismScore: 0.62,
  },
  {
    apiReadiness: 0.8,
    cameraScore: 0.72,
    costTier: "premium",
    environmentComplexitySupport: 0.69,
    failureRate: 0.08,
    id: "kling",
    maxDuration: 10,
    motionScore: 0.64,
    name: "Kling",
    offlineLocalSupport: false,
    portraitSupport: 0.96,
    queueSpeed: 0.44,
    queueStability: 0.79,
    realismScore: 0.94,
  },
  {
    apiReadiness: 0.76,
    cameraScore: 0.88,
    costTier: "medium",
    environmentComplexitySupport: 0.72,
    failureRate: 0.11,
    id: "ltx",
    maxDuration: 8,
    motionScore: 0.95,
    name: "LTX",
    offlineLocalSupport: true,
    portraitSupport: 0.58,
    queueSpeed: 0.82,
    queueStability: 0.71,
    realismScore: 0.61,
  },
  {
    apiReadiness: 0.88,
    cameraScore: 0.76,
    costTier: "premium",
    environmentComplexitySupport: 0.83,
    failureRate: 0.06,
    id: "runway",
    maxDuration: 14,
    motionScore: 0.73,
    name: "Runway",
    offlineLocalSupport: false,
    portraitSupport: 0.9,
    queueSpeed: 0.57,
    queueStability: 0.85,
    realismScore: 0.9,
  },
  {
    apiReadiness: 0.74,
    cameraScore: 0.68,
    costTier: "medium",
    environmentComplexitySupport: 0.65,
    failureRate: 0.13,
    id: "pika",
    maxDuration: 9,
    motionScore: 0.77,
    name: "Pika",
    offlineLocalSupport: false,
    portraitSupport: 0.71,
    queueSpeed: 0.79,
    queueStability: 0.63,
    realismScore: 0.57,
  },
  {
    apiReadiness: 1,
    cameraScore: 0.35,
    costTier: "low",
    environmentComplexitySupport: 0.45,
    failureRate: 0.02,
    id: "local-mock",
    maxDuration: 60,
    motionScore: 0.28,
    name: "Local Mock",
    offlineLocalSupport: true,
    portraitSupport: 0.4,
    queueSpeed: 1,
    queueStability: 1,
    realismScore: 0.2,
  },
];